spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password:
    driverClassName: org.h2.Driver

  jpa:
     hibernate.dialect: org.hibernate.dialect.H2Dialect
     hibernate.ddl-auto: update
     hibernate:
       jdbc: time_zone = TimeZone
     show-sql: true

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  jwt:
    header: Authorization
    #secret: my-very-secret-key
    secret: _M@d50n@r@uj0d@51lv@_
    #Token com duracao em minutos
    expiration: 30



  server:
    error:
      include-message: always



  main:
    allow-circular-references: true

#spring:
#  datasource:
#    url: jdbc:mysql://db:3306/clientes_db?useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true
#    username: root
#    password: maddytec@123



#  jackson:
#    default-property-inclusion: NON_NULL


